"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { ProtectedRoute } from "@/components/auth/protected-route";
import { createMilestone, deleteMilestone, getMilestones, updateMilestone } from "@/services/project.service";
import type { Milestone } from "@/types/project";

function Content() {
  const params = useParams<{ id: string }>();
  const id = Array.isArray(params.id) ? params.id[0] : params.id;
  const [items, setItems] = useState<Milestone[]>([]); const [title, setTitle] = useState(""); const [type, setType] = useState("RESEARCH"); const [dueDate, setDueDate] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null); const [editTitle, setEditTitle] = useState(""); const [editDueDate, setEditDueDate] = useState("");
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = useCallback(() => { setLoading(true); getMilestones(id).then((result) => setItems(result.milestones)).catch(() => setError("Unable to load milestones.")).finally(() => setLoading(false)); }, [id]);
  useEffect(() => { Promise.resolve().then(load); }, [load]);
  const add = async () => { setBusy(true); setError(""); try { await createMilestone(id, { title: title.trim(), description: "", type, order: items.length, dueDate: dueDate || undefined }); setTitle(""); setDueDate(""); setMessage("Milestone created successfully."); load(); } catch { setError("Unable to create milestone. Check the project and required fields."); } finally { setBusy(false); } };
  const startEdit = (milestone: Milestone) => { setEditingId(milestone._id); setEditTitle(milestone.title); setEditDueDate(milestone.dueDate ? milestone.dueDate.slice(0, 10) : ""); setError(""); };
  const saveEdit = async () => { if (!editingId || editTitle.trim().length < 2) return; setBusy(true); setError(""); try { await updateMilestone(id, editingId, { title: editTitle.trim(), dueDate: editDueDate || undefined }); setEditingId(null); setMessage("Milestone updated successfully."); load(); } catch { setError("Unable to update milestone."); } finally { setBusy(false); } };
  const changeStatus = async (milestone: Milestone) => { setBusy(true); setError(""); try { await updateMilestone(id, milestone._id, { status: milestone.status === "COMPLETED" ? "PENDING" : "COMPLETED" }); setMessage("Milestone status updated."); load(); } catch { setError("Unable to update milestone status."); } finally { setBusy(false); } };
  const remove = async (milestoneId: string) => { if (!window.confirm("Delete this milestone?")) return; setBusy(true); setError(""); try { await deleteMilestone(id, milestoneId); setMessage("Milestone deleted."); load(); } catch { setError("Unable to delete milestone."); } finally { setBusy(false); } };
  return <main className="mx-auto max-w-4xl px-5 py-16"><Link href={`/university/projects/${id}`} className="text-link">← Project workspace</Link><p className="eyebrow mt-10">Delivery planning</p><h1 className="display-md mt-3">Milestones</h1>{message && <p className="mt-5 border border-green-300/20 p-4 text-green-100" role="status">{message}</p>}{error && <p className="mt-5 text-red-200" role="alert">{error}</p>}
    <section className="mt-8 border border-white/10 p-5"><p className="eyebrow">Add milestone</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto_auto]"><input value={title} onChange={(event) => setTitle(event.target.value)} className="h-10 border border-white/15 bg-transparent px-3 text-white" placeholder="Milestone title" aria-label="Milestone title" /><select value={type} onChange={(event) => setType(event.target.value)} className="h-10 border border-white/15 bg-background px-3 text-white" aria-label="Milestone type"><option>RESEARCH</option><option>DESIGN</option><option>PROTOTYPE</option><option>TESTING</option><option>DEPLOYMENT</option></select><input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} className="h-10 border border-white/15 bg-transparent px-3 text-white" aria-label="Milestone due date" /></div><button className="button-primary mt-4" onClick={add} disabled={busy || title.trim().length < 2}>Add milestone</button></section>
    {loading ? <p className="mt-8 text-white/50">Loading milestones…</p> : <div className="mt-8 space-y-3">{!items.length && <p className="border border-dashed border-white/20 p-8 text-white/55">No milestones yet.</p>}{items.map((milestone) => <div key={milestone._id} className="border border-white/10 p-5">{editingId === milestone._id ? <div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><input value={editTitle} onChange={(event) => setEditTitle(event.target.value)} className="h-10 border border-white/15 bg-transparent px-3 text-white" aria-label="Edit milestone title" /><input type="date" value={editDueDate} onChange={(event) => setEditDueDate(event.target.value)} className="h-10 border border-white/15 bg-transparent px-3 text-white" aria-label="Edit milestone due date" /><div className="flex gap-2"><button className="button-primary" onClick={saveEdit} disabled={busy || editTitle.trim().length < 2}>Save</button><button className="button-secondary" onClick={() => setEditingId(null)} disabled={busy}>Cancel</button></div></div> : <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-white">{milestone.title}</p><p className="mt-1 text-xs uppercase tracking-widest text-white/45">{milestone.type} / {milestone.status}{milestone.dueDate ? ` / due ${new Date(milestone.dueDate).toLocaleDateString()}` : ""}</p></div><div className="flex flex-wrap gap-2"><button className="button-secondary" onClick={() => startEdit(milestone)} disabled={busy}>Edit</button><button className="button-secondary" onClick={() => changeStatus(milestone)} disabled={busy}>{milestone.status === "COMPLETED" ? "Mark pending" : "Mark complete"}</button><button className="button-secondary" onClick={() => remove(milestone._id)} disabled={busy}>Delete</button></div></div>}</div>)}</div>}
  </main>;
}
export default function Page() { return <ProtectedRoute allowedRole="UNIVERSITY"><Content /></ProtectedRoute>; }
