"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ProtectedRoute } from "@/components/auth/protected-route";
import { getStudentTeam } from "@/services/student.service";
import type { StudentTeam } from "@/types/project";

function Content(){const params=useParams<{id:string}>();const id=Array.isArray(params.id)?params.id[0]:params.id;const[team,setTeam]=useState<StudentTeam|null>(null);const[error,setError]=useState("");useEffect(()=>{getStudentTeam(id).then(setTeam).catch(()=>setError("Unable to load this team."))},[id]);if(error)return <main className="mx-auto max-w-5xl px-5 py-16"><p className="text-red-200" role="alert">{error}</p></main>;if(!team)return <main className="mx-auto max-w-5xl px-5 py-16"><p className="text-white/50">Loading team…</p></main>;const problem=typeof team.project.problem==="object"?team.project.problem:null;return <main className="mx-auto max-w-5xl px-5 py-16"><Link href="/student/teams" className="text-link">← My teams</Link><p className="eyebrow mt-10">Read-only team view / {team.project.status}</p><h1 className="display-md mt-3">{team.name}</h1><section className="mt-10 grid gap-5 sm:grid-cols-2"><Metric label="Project" value={team.project.title}/><Metric label="Progress" value={`${team.project.progress}%`}/><Metric label="Milestones" value={`${team.project.completedMilestones}/${team.project.totalMilestones}`}/><Metric label="Overdue" value={team.project.overdueMilestones}/></section><section className="mt-8 border border-white/10 p-6"><p className="eyebrow">Project</p><h2 className="mt-3 text-xl text-white">{team.project.title}</h2><p className="mt-4 leading-8 text-white/70">{team.project.description}</p><p className="mt-5 text-sm text-white/55">University: {typeof team.project.university==="string"?team.project.university:team.project.university.name||"University profile"}</p>{problem&&<div className="mt-5 border-t border-white/10 pt-5"><p className="eyebrow">Related societal problem</p><p className="mt-2 text-white">{problem.title}</p><p className="mt-2 text-sm text-white/60">{problem.category} · {problem.status}</p></div>}</section><section className="mt-6 border border-white/10 p-6"><p className="eyebrow">Team members</p><p className="mt-3 text-white/70">Leader: {typeof team.leader==="string"?team.leader:team.leader.name}</p><ul className="mt-4 space-y-2">{team.members.map((member,index)=><li key={`${team.id}-${index}`} className="border border-white/10 p-3 text-sm text-white/70">{typeof member.user==="string"?member.user:member.user.name} · {member.role}</li>)}</ul></section><p className="mt-6 text-sm text-white/45">This is a read-only student view. Project, team, and milestone changes are managed by the university project owner.</p></main>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="border border-white/10 p-5"><p className="eyebrow">{label}</p><p className="mt-2 text-xl text-white">{value}</p></div>}
export default function Page(){return <ProtectedRoute allowedRole="STUDENT"><Content/></ProtectedRoute>}
