export const PROBLEM_CATEGORIES = ["Education","Healthcare","Agriculture","Water Resources","Sanitation","Environment","Livelihoods","Accessibility","Infrastructure","Public Services"] as const;
export const PROBLEM_PRIORITIES = ["LOW","MEDIUM","HIGH","CRITICAL"] as const;
export type ProblemCategory=(typeof PROBLEM_CATEGORIES)[number]; export type ProblemPriority=(typeof PROBLEM_PRIORITIES)[number]; export type ProblemStatus="SUBMITTED"|"VALIDATING"|"VALIDATED"|"REJECTED"|"MATCHED"|"IN_PROGRESS"|"RESOLVED"|"ARCHIVED";
export interface ProblemAIAnalysis { status:"PENDING"|"COMPLETED"|"FAILED"; category?:string; confidence?:number; embeddingDimensions?:number; analyzedAt?:string; top_predictions?:{category:string;confidence:number}[] }
export interface ProblemDNA { affectedArea:string|null; affectedPeople:string|null; urgency:string|null; requiredDomains:string[]; requiredSkills:string[]; requiredResources:string[]; potentialCollaborationType:string|null }
export interface ProblemMatch { overallMatchScore:number; semanticScore:number; domainScore:number; skillsScore:number; resourceScore:number; locationScore:number; matchingReasons:string[]; missingCapabilities:string[] }
export interface Problem { id:string; title:string; description:string; category:ProblemCategory; location:{city:string;state:string;country:string;type?:"Point";coordinates?:[number,number]}; evidence:{description?:string;reference?:string}[]; priority:ProblemPriority; status:ProblemStatus; aiAnalysis?:ProblemAIAnalysis; dna?:ProblemDNA; match?:ProblemMatch; submittedBy?:{id:string;name:string;email:string;role:string}; rejectionReason?:string; validatedAt?:string; rejectedAt?:string; createdAt:string; updatedAt:string }
export interface ProblemProgressProject { id:string; title:string; description:string; status:string; university:{name?:string;profileLocation?:{city?:string;state?:string;country?:string}}|string; team?:{name:string;leader?:{name?:string;email?:string};members?:{user:{name?:string;email?:string;role?:string}}[]}|null; progress:number; totalMilestones:number; completedMilestones:number; pendingMilestones:number; overdueMilestones:number; startDate?:string; targetEndDate?:string }
export interface ProblemProgress { problem:{id:string;title:string;status:ProblemStatus;category:ProblemCategory;location?:{city?:string;state?:string;country?:string};aiAnalysisStatus?:ProblemAIAnalysis["status"];createdAt:string;updatedAt:string}; interests:{id:string;status:string;university:{name?:string;profileLocation?:{city?:string;state?:string;country?:string}}|string}[]; projects:ProblemProgressProject[] }
export interface CreateProblemInput {title:string;description:string;category:ProblemCategory;location:{city:string;state:string;country:string;type?:"Point";coordinates?:[number,number]};evidence?:{description?:string;reference?:string};priority:ProblemPriority}
