"use client";

import axios from "axios";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useForm, type UseFormRegister } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { ProtectedRoute } from "@/components/auth/protected-route";
import { getUniversityProfile, updateUniversityProfile } from "@/services/university.service";

const schema = z.object({ institutionName: z.string().trim().min(2, "Institution name is required"), description: z.string().max(5000), city: z.string().max(120), state: z.string().max(120), country: z.string().max(120), domains: z.string(), researchAreas: z.string(), skills: z.string(), resources: z.string(), collaborationInterests: z.string() });
type Form = z.infer<typeof schema>;
const split = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);
const emptyForm: Form = { institutionName: "", description: "", city: "", state: "", country: "", domains: "", researchAreas: "", skills: "", resources: "", collaborationInterests: "" };

function Content() {
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const { register, handleSubmit, reset, formState: { errors } } = useForm<Form>({ resolver: zodResolver(schema), defaultValues: emptyForm });
  useEffect(() => { getUniversityProfile().then((profile) => { if (profile) reset({ institutionName: profile.institutionName, description: profile.description, city: profile.location.city ?? "", state: profile.location.state ?? "", country: profile.location.country ?? "", domains: profile.domains.join(", "), researchAreas: profile.researchAreas.join(", "), skills: profile.skills.join(", "), resources: profile.resources.join(", "), collaborationInterests: profile.collaborationInterests.join(", ") }); }).catch(() => setError("Unable to load your university profile.")).finally(() => setLoading(false)); }, [reset]);
  const submit = async (value: Form) => { setSaving(true); setError(""); setMessage(""); try { const saved = await updateUniversityProfile({ institutionName: value.institutionName, description: value.description, location: { city: value.city.trim(), state: value.state.trim(), country: value.country.trim() }, domains: split(value.domains), researchAreas: split(value.researchAreas), skills: split(value.skills), resources: split(value.resources), collaborationInterests: split(value.collaborationInterests) }); reset({ institutionName: saved.institutionName, description: saved.description, city: saved.location.city ?? "", state: saved.location.state ?? "", country: saved.location.country ?? "", domains: saved.domains.join(", "), researchAreas: saved.researchAreas.join(", "), skills: saved.skills.join(", "), resources: saved.resources.join(", "), collaborationInterests: saved.collaborationInterests.join(", ") }); setMessage("University profile saved successfully."); } catch (requestError) { const apiMessage = axios.isAxiosError(requestError) && typeof requestError.response?.data?.message === "string" ? requestError.response.data.message : "Unable to save your profile."; setError(apiMessage); } finally { setSaving(false); } };
  if (loading) return <main className="mx-auto max-w-4xl px-5 py-16"><p className="text-white/50">Loading profile…</p></main>;
  return <main className="mx-auto max-w-4xl px-5 py-16"><Link href="/university" className="text-link">← University workspace</Link><p className="eyebrow mt-10">University capability profile</p><h1 className="display-md mt-3">Matching profile</h1><p className="body-copy mt-5">Use comma-separated values for domains, research areas, skills, and resources. These fields drive explainable opportunity matching.</p>{message && <p className="mt-6 border border-green-300/20 p-4 text-green-100" role="status">{message}</p>}{error && <p className="mt-6 text-red-200" role="alert">{error}</p>}<form onSubmit={handleSubmit(submit)} className="mt-10 space-y-6"><Field label="Institution name" name="institutionName" register={register} error={errors.institutionName?.message}/><Field label="Description" name="description" register={register} error={errors.description?.message} area/><div className="grid gap-5 md:grid-cols-3"><Field label="City" name="city" register={register} error={errors.city?.message}/><Field label="State" name="state" register={register} error={errors.state?.message}/><Field label="Country" name="country" register={register} error={errors.country?.message}/></div><div className="grid gap-5 md:grid-cols-2">{([ ["domains", "Domains"], ["researchAreas", "Research areas"], ["skills", "Skills"], ["resources", "Resources"], ["collaborationInterests", "Collaboration interests"] ] as const).map(([name, label]) => <Field key={name} label={label} name={name} register={register} error={errors[name]?.message} placeholder="e.g. water systems, public health"/>)}</div><button type="submit" className="button-primary" disabled={saving}>{saving ? "Saving…" : "Save profile"}</button></form></main>;
}

function Field({ label, name, register, error, area, placeholder }: { label: string; name: keyof Form; register: UseFormRegister<Form>; error?: string; area?: boolean; placeholder?: string }) { const props = register(name); return <div><label className="eyebrow" htmlFor={name}>{label}</label>{area ? <textarea id={name} {...props} placeholder={placeholder} className="mt-2 min-h-28 w-full border border-white/15 bg-transparent p-3 text-white outline-none focus:border-blue-300"/> : <input id={name} {...props} placeholder={placeholder} className="mt-2 h-10 w-full border border-white/15 bg-transparent px-3 text-white outline-none focus:border-blue-300"/>}{error && <p className="mt-2 text-sm text-red-200" role="alert">{error}</p>}</div>; }
export default function Page() { return <ProtectedRoute allowedRole="UNIVERSITY"><Content /></ProtectedRoute>; }
