import { Types } from "mongoose";
import { Collaboration, Industry, Project, University } from "../models";
import { AppError } from "../utils/app-error";

function oid(value: string) { if (!Types.ObjectId.isValid(value)) throw new AppError("Invalid collaboration ID", 400); return new Types.ObjectId(value); }
async function ownedProject(userId: string, collaborationId: string) { const collaboration = await Collaboration.findById(oid(collaborationId)).populate("industry", "name description profileLocation"); if (!collaboration) throw new AppError("Collaboration request not found", 404); const university = await University.findOne({ user: userId }); if (!university) throw new AppError("University profile required", 400); const project = await Project.findOne({ _id: collaboration.project, university: university._id }).populate("problem", "title category status"); if (!project) throw new AppError("Collaboration request not found", 404); return { collaboration, project }; }
export async function listForUniversity(userId: string) { const university = await University.findOne({ user: userId }); if (!university) throw new AppError("University profile required", 400); return Collaboration.find({ project: { $in: await Project.find({ university: university._id }).distinct("_id") } }).populate("industry", "name description profileLocation").populate("project", "title status problem").sort({ createdAt: -1 }); }
async function respond(userId: string, collaborationId: string, status: "ACCEPTED" | "REJECTED") { const { collaboration } = await ownedProject(userId, collaborationId); if (collaboration.status !== "PENDING") throw new AppError("Only pending collaboration requests can be changed", 400); collaboration.status = status; collaboration.respondedAt = new Date(); collaboration.respondedBy = new Types.ObjectId(userId); await collaboration.save(); return collaboration; }
export const accept = (userId: string, id: string) => respond(userId, id, "ACCEPTED");
export const reject = (userId: string, id: string) => respond(userId, id, "REJECTED");
