import { Types } from "mongoose";
import { Collaboration, Industry, Milestone, Problem, Project, Solution, Team, University } from "../models";
import { AppError } from "../utils/app-error";
import { calculateOpportunityMatch } from "./opportunity-matching.service";
import { create as createNotification } from "./notification.service";
import type { IndustryProfileInput } from "../validators/industry.validators";

const oid = (value: string) => { if (!Types.ObjectId.isValid(value)) throw new AppError("Invalid ID", 400); return new Types.ObjectId(value); };
const profile = (u: any) => u ? ({ id: u._id.toString(), organizationName: u.name, description: u.description ?? "", industryType: u.industryType ?? "", location: u.profileLocation ?? {}, domains: u.expertise ?? [], expertise: u.expertise ?? [], technologies: u.technologies ?? [], skills: u.skills ?? [], resources: u.resources ?? [], facilities: u.facilities ?? [], collaborationInterests: u.collaborationInterests ?? [], isActive: u.isActive, createdAt: u.createdAt, updatedAt: u.updatedAt }) : null;
async function industry(userId: string) { const value = await Industry.findOne({ user: oid(userId) }); if (!value) throw new AppError("Complete your industry profile first", 400); return value; }
async function stats(projectId: Types.ObjectId) { const ms = await Milestone.find({ project: projectId }); const completed = ms.filter((m) => m.status === "COMPLETED").length; return { progress: ms.length ? Math.round(completed / ms.length * 100) : 0, totalMilestones: ms.length, completedMilestones: completed, pendingMilestones: ms.length - completed, overdueMilestones: ms.filter((m) => m.dueDate && m.dueDate < new Date() && m.status !== "COMPLETED").length }; }
function safeProblem(p: any, match?: any, project?: any) { return { id: p._id.toString(), title: p.title, description: p.description, category: p.category, location: p.location, priority: p.priority, status: p.status, dna: { affectedArea: p.location ? [p.location.city, p.location.state, p.location.country].filter(Boolean).join(", ") : null, affectedPeople: null, urgency: p.priority ?? null, requiredDomains: [p.category], requiredSkills: [], requiredResources: [], potentialCollaborationType: null }, aiAnalysis: { status: p.aiAnalysisStatus, category: p.aiClassification, confidence: p.aiConfidence }, project: project ?? null, match: match ?? null, createdAt: p.createdAt, updatedAt: p.updatedAt }; }
async function match(ind: any, problem: any) { if (!problem.embedding?.length) return null; if (![ind.description, ...ind.expertise, ...ind.technologies, ...ind.skills, ...ind.resources, ...ind.facilities, ...ind.collaborationInterests].some(Boolean)) return null; return calculateOpportunityMatch(problem, ind, "industry"); }
async function projectForProblem(problemId: Types.ObjectId) { const project = await Project.findOne({ problem: problemId, status: { $ne: "CANCELLED" } }).populate("university", "name domains researchAreas profileLocation").sort({ createdAt: -1 }); if (!project) return null; const [team, progress] = await Promise.all([Team.findOne({ project: project._id }).populate("leader", "name email role").populate("members.user", "name email role"), stats(project._id)]); return { id: project._id.toString(), title: project.title, description: project.description, status: project.status, university: project.university, startDate: project.startDate, targetEndDate: project.targetEndDate, team, ...progress }; }
export async function getProfile(userId: string) { return profile(await Industry.findOne({ user: oid(userId) })); }
export async function saveProfile(userId: string, input: IndustryProfileInput) {
  const user = oid(userId);
  const value = await Industry.findOneAndUpdate(
    { user },
    { $set: { name: input.organizationName, description: input.description, industryType: input.industryType, profileLocation: input.location, expertise: input.domains.concat(input.expertise), technologies: input.technologies, skills: input.skills, resources: input.resources, facilities: input.facilities, collaborationInterests: input.collaborationInterests, capabilities: input.skills } },
      { upsert: true, returnDocument: "after", setDefaultsOnInsert: true, runValidators: true },
  );
  if (!value) throw new AppError("Unable to save industry profile", 500);
  return profile(value);
}
export async function opportunities(userId: string, query: any) { const ind = await industry(userId); const filter: any = { status: "VALIDATED" }; if (query.category) filter.category = query.category; if (query.search) filter.$or = [{ title: new RegExp(query.search, "i") }, { description: new RegExp(query.search, "i") }]; const [items, total] = await Promise.all([Problem.find(filter).sort({ createdAt: -1 }).skip((query.page - 1) * query.limit).limit(query.limit), Problem.countDocuments(filter)]); const results = await Promise.all(items.map(async (p) => safeProblem(p, await match(ind, p), await projectForProblem(p._id)))); return { opportunities: results, pagination: { page: query.page, limit: query.limit, total, pages: Math.ceil(total / query.limit) } }; }
export async function opportunity(userId: string, problemId: string) { const ind = await industry(userId); const p = await Problem.findOne({ _id: oid(problemId), status: "VALIDATED" }); if (!p) throw new AppError("Validated problem not found", 404); return safeProblem(p, await match(ind, p), await projectForProblem(p._id)); }
export async function requestInterest(userId: string, projectId: string, message: string) { const ind = await industry(userId); const project = await Project.findOne({ _id: oid(projectId), status: { $ne: "CANCELLED" } }).populate("problem", "title status"); if (!project) throw new AppError("Project not found", 404); if (!project.problem || (project.problem as any).status !== "VALIDATED") throw new AppError("Only projects linked to validated problems can receive interest", 400); const existing = await Collaboration.findOne({ project: project._id, industry: ind._id }); if (existing) return { collaboration: existing, project }; const collaboration = await Collaboration.create({ project: project._id, industry: ind._id, requestedBy: oid(userId), message, type: "RESOURCE_SUPPORT", status: "PENDING" }); const university = await University.findById(project.university).select("user"); if (university?.user) await createNotification({ recipient: university.user.toString(), title: "New industry collaboration request", message: `${ind.name} requested to collaborate on “${project.title}”.`, type: "COLLABORATION_REQUEST", relatedType: "PROJECT", relatedId: project._id, dedupeKey: `collaboration-request:${collaboration._id}` }); return { collaboration, project }; }
export async function collaborations(userId: string) { const ind = await industry(userId); return Collaboration.find({ industry: ind._id }).populate("project", "title description status problem university startDate targetEndDate").sort({ createdAt: -1 }); }
export async function industryProject(userId: string, projectId: string) { const ind = await industry(userId); const collaboration = await Collaboration.findOne({ industry: ind._id, project: oid(projectId), status: "ACCEPTED" }); if (!collaboration) throw new AppError("Accepted collaboration not found", 403); const project = await Project.findById(projectId).populate("problem", "title description category location status").populate("university", "name profileLocation"); if (!project) throw new AppError("Project not found", 404); const solutions = await Solution.find({ project: project._id }).select("title description approach expectedOutcome requiredResources status createdAt updatedAt").sort({ createdAt: -1 }); return { collaboration, project, solutions, team: await Team.findOne({ project: project._id }).populate("leader", "name email role").populate("members.user", "name email role"), ...(await stats(project._id)) }; }
