import { Types } from "mongoose";
import { Milestone, Problem, Project, Team, University, UniversityInterest, User } from "../models";
import { AppError } from "../utils/app-error";
import type { ProjectCreateInput } from "../validators/project.validators";

const oid=(value:string)=>{if(!Types.ObjectId.isValid(value))throw new AppError("Invalid ID",400);return new Types.ObjectId(value)};
const transitions:Record<string,string[]>={PROPOSED:["ACTIVE","CANCELLED"],ACTIVE:["ON_HOLD","COMPLETED","CANCELLED"],ON_HOLD:["ACTIVE","CANCELLED"],COMPLETED:[],CANCELLED:[]};
async function universityFor(userId:string){const u=await University.findOne({user:userId});if(!u)throw new AppError("University profile required",400);return u}
async function owned(userId:string,projectId:string){const u=await universityFor(userId);const p=await Project.findOne({_id:oid(projectId),university:u._id});if(!p)throw new AppError("Project not found",404);return {university:u,project:p}}
async function progress(projectId:Types.ObjectId){const ms=await Milestone.find({project:projectId});const completed=ms.filter(x=>x.status==="COMPLETED").length;return {progress:ms.length?Math.round(completed/ms.length*100):0,totalMilestones:ms.length,completedMilestones:completed,pendingMilestones:ms.length-completed,overdueMilestones:ms.filter(x=>x.dueDate&&x.dueDate<new Date()&&x.status!=="COMPLETED").length}}
async function safe(p:any){const [ms,team,stats]=await Promise.all([Milestone.find({project:p._id}).sort({order:1,dueDate:1}),Team.findOne({project:p._id}).populate("leader","name email").populate("members.user","name email role"),progress(p._id)]);return {id:p._id.toString(),title:p.title,description:p.description,problem:p.problem,university:p.university,createdBy:p.createdBy,startDate:p.startDate,targetEndDate:p.targetEndDate,status:p.status,team,milestones:ms,...stats,createdAt:p.createdAt,updatedAt:p.updatedAt}}
export async function create(userId:string,input:ProjectCreateInput){const u=await universityFor(userId);const problem=await Problem.findOne({_id:oid(input.problemId),status:"VALIDATED"});if(!problem)throw new AppError("Only validated problems can become projects",400);const interest=await UniversityInterest.findOne({university:u._id,problem:problem._id});if(!interest)throw new AppError("Express interest before creating a project",403);const duplicate=await Project.findOne({university:u._id,problem:problem._id,status:{$nin:["CANCELLED"]}});if(duplicate)throw new AppError("An active project already exists for this problem",409);const p=await Project.create({title:input.title,description:input.description,problem:problem._id,university:u._id,createdBy:new Types.ObjectId(userId),startDate:input.startDate,targetEndDate:input.targetEndDate,status:"PROPOSED"});await p.populate("problem","title category location status");return safe(p)}
export async function list(userId:string,q:any){const u=await universityFor(userId);const filter:any={university:u._id};if(q.status)filter.status=q.status;if(q.search)filter.$or=[{title:new RegExp(q.search,"i")},{description:new RegExp(q.search,"i")}];const [items,total]=await Promise.all([Project.find(filter).populate("problem","title category location status").populate("university","name").populate("createdBy","name email").sort({createdAt:-1}).skip((q.page-1)*q.limit).limit(q.limit),Project.countDocuments(filter)]);return {projects:await Promise.all(items.map(safe)),pagination:{page:q.page,limit:q.limit,total,pages:Math.ceil(total/q.limit)}}}
export async function detail(userId:string,id:string){const {project}=await owned(userId,id);await project.populate("problem","title category location status");await project.populate("university","name");await project.populate("createdBy","name email");return safe(project)}
export async function update(userId:string,id:string,input:any){const {project}=await owned(userId,id);if(["COMPLETED","CANCELLED"].includes(project.status))throw new AppError("This project cannot be edited",400);Object.assign(project,input);await project.save();return safe(project)}
export async function setStatus(userId:string,id:string,status:string){const {project}=await owned(userId,id);if(!transitions[project.status]?.includes(status))throw new AppError(`Invalid project status transition: ${project.status} to ${status}`,400);project.status=status;await project.save();return safe(project)}
export async function createTeam(userId:string,id:string,name:string){const {university,project}=await owned(userId,id);if(["COMPLETED","CANCELLED"].includes(project.status))throw new AppError("This project cannot have a team",400);if(await Team.exists({project:project._id}))throw new AppError("A team already exists for this project",409);const team=await Team.create({project:project._id,university:university._id,name,leader:new Types.ObjectId(userId),members:[{user:new Types.ObjectId(userId),role:"LEADER"}]});project.studentTeam=team._id;await project.save();return team}
export async function getTeam(userId:string,id:string){const {project}=await owned(userId,id);const team=await Team.findOne({project:project._id}).populate("leader","name email").populate("members.user","name email role");if(!team)throw new AppError("Team not found",404);return team}
export async function addMember(userId:string,id:string,memberId:string){const {project}=await owned(userId,id);const team=await Team.findOne({project:project._id});if(!team)throw new AppError("Team not found",404);const member=oid(memberId);if(team.members.some((x:any)=>x.user.toString()===member.toString()))throw new AppError("User is already a team member",409);const user=await User.findById(member).select("name email role isActive");if(!user||!user.isActive)throw new AppError("User not found",404);if(!["STUDENT","UNIVERSITY"].includes(user.role))throw new AppError("Only Student or University users can join this team",403);if(user.role==="UNIVERSITY"){const profile=await University.findOne({user:member});if(!profile?.name)throw new AppError("This University user must complete an institution profile first",400)}team.members.push({user:member,role:"MEMBER",joinedAt:new Date()} as any);await team.save();return getTeam(userId,id)}
export async function removeMember(userId:string,id:string,memberId:string){const {project}=await owned(userId,id);const team=await Team.findOne({project:project._id});if(!team)throw new AppError("Team not found",404);if(team.leader.toString()===memberId)throw new AppError("Transfer leadership before removing the team leader",400);team.members=team.members.filter((x:any)=>x.user.toString()!==memberId) as any;await team.save();return getTeam(userId,id)}
export async function listMilestones(userId:string,id:string){const {project}=await owned(userId,id);return {milestones:await Milestone.find({project:project._id}).sort({order:1,dueDate:1}),...(await progress(project._id))}}
export async function addMilestone(userId:string,id:string,input:any){const {project}=await owned(userId,id);const m=await Milestone.create({...input,project:project._id});return m}
export async function updateMilestone(userId:string,id:string,mid:string,input:any){const {project}=await owned(userId,id);const m=await Milestone.findOne({_id:oid(mid),project:project._id});if(!m)throw new AppError("Milestone not found",404);Object.assign(m,input);if(input.status==="COMPLETED"&&!input.completedAt)m.completedAt=new Date();if(input.status&&input.status!=="COMPLETED")m.completedAt=undefined;await m.save();return m}
export async function deleteMilestone(userId:string,id:string,mid:string){const {project}=await owned(userId,id);const result=await Milestone.deleteOne({_id:oid(mid),project:project._id});if(!result.deletedCount)throw new AppError("Milestone not found",404);return {deleted:true}}
