import { Types } from "mongoose";
import { Problem, University, UniversityInterest, Project, User } from "../models";
import { AppError } from "../utils/app-error";
import { generateEmbedding } from "./ai/aiClient";
import { create as createNotification } from "./notification.service";
import type { UniversityProfileInput } from "../validators/university.validators";

const WEIGHTS = { semantic: .4, domain: .25, skills: .2, resource: .1, location: .05 } as const;
function id(value: string) { if (!Types.ObjectId.isValid(value)) throw new AppError("Invalid problem ID", 400); return new Types.ObjectId(value); }
function tokens(values: string[]) { return new Set(values.join(" ").toLowerCase().split(/[^a-z0-9]+/).filter((x) => x.length > 2)); }
function overlap(required: string[], available: string[]) { const a=tokens(required); const b=tokens(available); return a.size ? [...a].filter((x)=>b.has(x)).length/a.size : 0; }
function dna(problem: any) { return { problemId: problem._id.toString(), title: problem.title, category: problem.category, description: problem.description, location: problem.location, affectedArea: problem.location ? [problem.location.city, problem.location.state, problem.location.country].filter(Boolean).join(", ") : null, affectedPeople: null, urgency: problem.priority ?? null, requiredSkills: [], requiredDomains: [problem.category], requiredResources: [], potentialCollaborationType: null }; }
function safe(problem: any, match?: any) { return { id: problem._id.toString(), title: problem.title, description: problem.description, category: problem.category, location: problem.location, priority: problem.priority, status: problem.status, aiAnalysis: { status: problem.aiAnalysisStatus, category: problem.aiClassification, confidence: problem.aiConfidence, analyzedAt: problem.aiAnalyzedAt }, dna: dna(problem), createdAt: problem.createdAt, updatedAt: problem.updatedAt, ...(match ? { match } : {}) }; }
export async function getProfile(userId: string) { const university = await University.findOne({ user: userId }); return university ? profile(university) : null; }
function profile(u: any) { return { id: u._id.toString(), institutionName: u.name, description: u.description ?? "", location: u.profileLocation ?? {}, domains: u.domains ?? [], researchAreas: u.researchAreas ?? [], skills: u.skills ?? [], resources: u.resources ?? [], collaborationInterests: u.collaborationInterests ?? [], isActive: u.isActive, createdAt: u.createdAt, updatedAt: u.updatedAt }; }
export async function saveProfile(userId: string, input: UniversityProfileInput) { const u=await University.findOneAndUpdate({user:userId}, {user:new Types.ObjectId(userId), name:input.institutionName, description:input.description, profileLocation:input.location, domains:input.domains, researchAreas:input.researchAreas, skills:input.skills, resources:input.resources, collaborationInterests:input.collaborationInterests, departments:input.domains, expertise:input.researchAreas, capabilities:input.skills}, {new:true,upsert:true,setDefaultsOnInsert:true}); return profile(u); }
async function university(userId: string) { const u=await University.findOne({user:userId}); if (!u) throw new AppError("Complete your university profile first", 400); return u; }
export async function listProblems(userId: string, query: any) { const filter:any={status:"VALIDATED"}; if(query.category)filter.category=query.category; if(query.location)filter.$or=[{"location.city":new RegExp(query.location,"i")},{"location.state":new RegExp(query.location,"i")},{"location.country":new RegExp(query.location,"i")}]; if(query.search)filter.$and=[{$or:[{title:new RegExp(query.search,"i")},{description:new RegExp(query.search,"i")}]}]; const [items,total]=await Promise.all([Problem.find(filter).sort({createdAt:-1}).skip((query.page-1)*query.limit).limit(query.limit),Problem.countDocuments(filter)]); return {problems:items.map((p)=>safe(p)),pagination:{page:query.page,limit:query.limit,total,pages:Math.ceil(total/query.limit)}}; }
export async function getProblem(userId: string, problemId: string) { await university(userId); const p=await Problem.findOne({_id:id(problemId),status:"VALIDATED"}); if(!p)throw new AppError("Validated problem not found",404); return safe(p, await match(userId,p)); }
async function match(userId: string, problem: any) { const u=await university(userId); if(!problem.embedding?.length) throw new AppError("Problem embedding is unavailable",503); const text=[u.description,...u.domains,...u.researchAreas,...u.skills,...u.resources,...u.collaborationInterests].join(" "); let emb; try { emb=await generateEmbedding(text); } catch { throw new AppError("AI matching service is unavailable",503); } const dot=problem.embedding.reduce((s:number,v:number,i:number)=>s+v*emb.embedding[i],0); const norm=(a:number[])=>Math.sqrt(a.reduce((s,v)=>s+v*v,0)); const semantic=Math.max(0,Math.min(1,dot/(norm(problem.embedding)*norm(emb.embedding)||1))); const d=overlap([problem.category], [...u.domains,...u.researchAreas,...u.expertise]); const skills=overlap([problem.category, ...problem.description.split(/\s+/).slice(0,8)], [...u.skills,...u.researchAreas]); const resource=overlap([problem.category],u.resources); const location=overlap([problem.location?.country??"",problem.location?.state??""],[u.profileLocation?.country??"",u.profileLocation?.state??""]); const score=semantic*WEIGHTS.semantic+d*WEIGHTS.domain+skills*WEIGHTS.skills+resource*WEIGHTS.resource+location*WEIGHTS.location; const reasons:string[]=[]; if(semantic>=.6)reasons.push("Strong semantic alignment with the university profile"); if(d>0)reasons.push("Research domain aligns with the problem category"); if(skills>0)reasons.push("Relevant skills or research areas are available"); if(resource>0)reasons.push("Listed resources overlap with the problem domain"); const missing:string[]=[]; if(!skills)missing.push("Problem-specific skills are not listed in the profile"); if(!resource)missing.push("Relevant resources are not listed in the profile"); return {overallMatchScore:score,semanticScore:semantic,domainScore:d,skillsScore:skills,resourceScore:resource,locationScore:location,matchingReasons:reasons,missingCapabilities:missing}; }
export async function getMatches(userId:string) { const q=await listProblems(userId,{status:"VALIDATED",page:1,limit:100}); const results=[]; for(const p of q.problems){ try { results.push({problem:p,match:await match(userId,await Problem.findById(p.id))}); } catch(e) { if(e instanceof AppError && e.statusCode===503) throw e; } } return results.sort((a,b)=>b.match.overallMatchScore-a.match.overallMatchScore); }
export async function searchMembers(userId:string, query:string) { await university(userId); const q=query.trim(); if(q.length<2)return []; const users=await User.find({role:{$in:["STUDENT","UNIVERSITY"]},isActive:true,$or:[{name:new RegExp(q,"i")},{email:new RegExp(q,"i")}]}).select("name email role").limit(20).lean(); return users.map((u:any)=>({id:u._id.toString(),name:u.name,email:u.email,role:u.role})); }
export async function interest(userId:string, problemId:string) { const u=await university(userId); const p=await Problem.findOne({_id:id(problemId),status:"VALIDATED"}); if(!p)throw new AppError("Only validated problems can receive interest",400); const existing=await UniversityInterest.findOne({university:u._id,problem:p._id}); let interest=existing; if(!interest) interest=await UniversityInterest.create({university:u._id,problem:p._id,status:"PENDING"}); let project=await Project.findOne({university:u._id,problem:p._id,status:{$nin:["CANCELLED"]}}); if(!project) project=await Project.create({title:`Project: ${p.title}`,description:`University-led project created from interest in the validated problem: ${p.title}`,problem:p._id,university:u._id,createdBy:new Types.ObjectId(userId),status:"PROPOSED"}); if(!existing) await createNotification({recipient:p.submittedBy.toString(),title:"University interest received",message:`${u.name} expressed interest in your problem “${p.title}”.`,type:"UNIVERSITY_INTEREST",relatedType:"PROBLEM",relatedId:p._id,dedupeKey:`university-interest:${interest._id}`}); if(project) await createNotification({recipient:p.submittedBy.toString(),title:"University project created",message:`A university project is now associated with “${p.title}”.`,type:"PROJECT_CREATED",relatedType:"PROJECT",relatedId:project._id,dedupeKey:`project-created:${project._id}`}); return {interest,project}; }
