"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { ProtectedRoute } from "@/components/auth/protected-route";
import { createRevivalReview, getRevival, updateRevivalReview } from "@/services/revival.service";
import type { RevivalDetail, RevivalStatus } from "@/types/revival";
function Content() { const params = useParams<{ id: string }>(); const id = Array.isArray(params.id) ? params.id[0] : params.id; const [data, setData] = useState<RevivalDetail | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const load = useCallback(() => getRevival(id).then(setData).catch(() => setError("Unable to load revival review.")), [id]); useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]); const change = async (status: RevivalStatus) => { setBusy(true); try { const review = data?.review ? await updateRevivalReview(id, { status }) : await createRevivalReview(id, { proposedActions: [] }); setData((current) => current ? { ...current, review } : current); } catch { setError("Unable to update revival review."); } finally { setBusy(false); } }; return <main className="mx-auto max-w-5xl px-5 py-16"><Link href="/admin/revival" className="text-link">← Revival candidates</Link>{error && <p className="mt-8 text-red-200" role="alert">{error}</p>}{!data && !error && <p className="mt-10 text-white/55">Loading…</p>}{data && <><p className="eyebrow mt-10">Revival review / {data.problem.status}</p><h1 className="display-md mt-3">{data.problem.title}</h1><section className="mt-10 border border-white/10 p-6"><p className="eyebrow">Why flagged</p><ul className="mt-4 list-disc pl-5 text-white/70">{data.detection.signals.map((signal) => <li key={signal}>{signal}</li>)}</ul><p className="mt-5 text-sm text-white/50">Last activity: {new Date(data.detection.lastActivityAt).toLocaleString()}</p></section><section className="mt-6 border border-blue-300/20 p-6"><p className="eyebrow">Evidence-based next steps</p><ul className="mt-4 list-disc pl-5 text-white/70">{data.recommendations.actions.map((action) => <li key={action}>{action}</li>)}</ul></section><section className="mt-6 border border-white/10 p-6"><p className="eyebrow">Review status</p><p className="mt-3 text-white">{data.review?.status ?? "Not started"}</p><div className="mt-5 flex flex-wrap gap-3"><button className="button-secondary" disabled={busy} onClick={() => void change(data.review ? "REVIVAL_PROPOSED" : "UNDER_REVIEW")}>{data.review ? "Propose revival" : "Start review"}</button><button className="button-primary" disabled={busy || !data.review} onClick={() => void change("REVIVAL_IN_PROGRESS")}>Start revival</button></div></section></>}</main>; }
export default function Page() { return <ProtectedRoute allowedRole={["ADMIN", "UNIVERSITY", "INDUSTRY"]}><Content /></ProtectedRoute>; }
