import { Router } from "express";
import { requireAuth, requireRole } from "../middleware/auth";
import { asyncHandler } from "../middleware/asyncHandler";
import { create, getMine, getPassport, getProgress, listMine } from "../controllers/problem.controller";
import * as dna from "../controllers/problem-dna.controller";
import * as opportunities from "../controllers/opportunity.controller";
const router = Router();
const citizen = [requireAuth, requireRole("CITIZEN", "STUDENT")];
router.get("/:id/passport", requireAuth, asyncHandler(getPassport));
router.post("/:id/dna/generate", requireAuth, asyncHandler(dna.generate));
router.get("/:id/dna/status", requireAuth, asyncHandler(dna.status));
router.get("/:id/dna", requireAuth, asyncHandler(dna.get));
router.post("/:problemId/opportunities/generate", requireAuth, asyncHandler(opportunities.generate));
router.post("/:problemId/opportunities/refresh", requireAuth, asyncHandler(opportunities.refresh));
router.get("/:problemId/opportunities/:matchId", requireAuth, asyncHandler(opportunities.get));
router.get("/:problemId/opportunities", requireAuth, asyncHandler(opportunities.list));
router.post("/", ...citizen, asyncHandler(create));
router.get("/my", ...citizen, asyncHandler(listMine));
router.get("/:id/progress", ...citizen, asyncHandler(getProgress));
router.get("/:id", ...citizen, asyncHandler(getMine));
export default router;
