"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { ProtectedRoute } from "@/components/auth/protected-route";
import { getImpactTwin } from "@/services/impact.service";
import { createImpactIndicator, createImpactScenario, recordImpactObservation } from "@/services/impact.service";
import { useAuth } from "@/hooks/use-auth";
import type { ImpactTwin } from "@/types/impact";

function Content() {
  const params = useParams<{ id: string }>();
  const id = Array.isArray(params.id) ? params.id[0] : params.id;
  const [data, setData] = useState<ImpactTwin | null>(null);
  const [error, setError] = useState("");
  const { user } = useAuth();
  const [formMessage, setFormMessage] = useState("");
  const [indicatorName, setIndicatorName] = useState("");
  const [indicatorUnit, setIndicatorUnit] = useState("");
  const [baseline, setBaseline] = useState("");
  const [target, setTarget] = useState("");
  const [saving, setSaving] = useState(false);
  const [scenarioName, setScenarioName] = useState("");
  const [scenarioIntervention, setScenarioIntervention] = useState("");
  const [scenarioMethod, setScenarioMethod] = useState("");
  const load = useCallback(() => { if (!id) return; setError(""); getImpactTwin(id).then(setData).catch((e) => setError(e?.response?.data?.message ?? "Unable to load Impact Twin.")); }, [id]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const addIndicator = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setFormMessage(""); try { await createImpactIndicator(id, { name: indicatorName, unit: indicatorUnit, baselineValue: Number(baseline), targetValue: target === "" ? null : Number(target) }); setIndicatorName(""); setIndicatorUnit(""); setBaseline(""); setTarget(""); setFormMessage("Impact indicator saved."); load(); } catch (e: unknown) { const message = (e as { response?: { data?: { message?: string } } })?.response?.data?.message; setFormMessage(message ?? "Unable to save indicator."); } finally { setSaving(false); } };
  const addScenario = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setFormMessage(""); try { await createImpactScenario(id, { name: scenarioName, proposedIntervention: scenarioIntervention, estimationMethod: scenarioMethod, expectedValues: {}, assumptions: [] }); setScenarioName(""); setScenarioIntervention(""); setScenarioMethod(""); setFormMessage("Scenario estimate saved."); load(); } catch (e: unknown) { const message = (e as { response?: { data?: { message?: string } } })?.response?.data?.message; setFormMessage(message ?? "Unable to save scenario."); } finally { setSaving(false); } };
  const addObservation = async (event: FormEvent, indicatorId: string) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); setSaving(true); setFormMessage(""); try { await recordImpactObservation(id, { indicatorId, observedValue: Number(form.get("observedValue")), measurementDate: form.get("measurementDate") }); setFormMessage("Observed measurement saved."); load(); } catch (e: unknown) { const message = (e as { response?: { data?: { message?: string } } })?.response?.data?.message; setFormMessage(message ?? "Unable to save observation."); } finally { setSaving(false); } };
  return <main className="mx-auto max-w-6xl px-5 py-16">
    <Link href={`/citizen/problems/${id}`} className="text-link">← Back to problem</Link>
    <p className="eyebrow mt-10">Impact Twin / Evidence-based tracking</p><h1 className="display-md mt-3">Challenge impact</h1>
    {error && <div className="mt-8 border border-red-300/30 p-5 text-red-100" role="alert">{error}<button onClick={load} className="button-secondary ml-4">Retry</button></div>}
    {!error && !data && <p className="mt-10 text-white/55">Loading impact data…</p>}
    {data && <>
      <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Indicators", data.summary.totalIndicators], ["Observed", data.summary.indicatorsWithObservations], ["Target progress", data.summary.targetProgress === null ? "—" : `${data.summary.targetProgress}%`], ["Data completeness", `${data.summary.dataCompleteness}%`]].map(([label, value]) => <div key={String(label)} className="border border-white/10 p-5"><p className="eyebrow">{label}</p><p className="mt-3 text-2xl text-white">{value}</p></div>)}</div>
      {user && ["ADMIN", "UNIVERSITY", "INDUSTRY"].includes(user.role) && <form onSubmit={addIndicator} className="mt-10 border border-blue-300/20 p-5"><p className="eyebrow">Define baseline indicator</p><div className="mt-4 grid gap-3 md:grid-cols-4"><input aria-label="Indicator name" required value={indicatorName} onChange={(e) => setIndicatorName(e.target.value)} placeholder="Indicator name" className="input" /><input aria-label="Unit" required value={indicatorUnit} onChange={(e) => setIndicatorUnit(e.target.value)} placeholder="Unit" className="input" /><input aria-label="Baseline value" required type="number" step="any" value={baseline} onChange={(e) => setBaseline(e.target.value)} placeholder="Baseline" className="input" /><input aria-label="Target value" type="number" step="any" value={target} onChange={(e) => setTarget(e.target.value)} placeholder="Target (optional)" className="input" /></div><button disabled={saving} className="button-primary mt-4">{saving ? "Saving…" : "Save indicator"}</button>{formMessage && <p className="mt-3 text-sm text-white/65" role="status">{formMessage}</p>}</form>}
      {user && ["ADMIN", "UNIVERSITY", "INDUSTRY"].includes(user.role) && <form onSubmit={addScenario} className="mt-5 border border-amber-300/20 p-5"><p className="eyebrow">Add scenario estimate</p><div className="mt-4 grid gap-3 md:grid-cols-3"><input aria-label="Scenario name" required value={scenarioName} onChange={(e) => setScenarioName(e.target.value)} placeholder="Scenario name" className="input" /><input aria-label="Proposed intervention" required value={scenarioIntervention} onChange={(e) => setScenarioIntervention(e.target.value)} placeholder="Proposed intervention" className="input" /><input aria-label="Estimation method" required value={scenarioMethod} onChange={(e) => setScenarioMethod(e.target.value)} placeholder="Estimation method" className="input" /></div><button disabled={saving} className="button-secondary mt-4">Save estimate</button></form>}
      <section className="mt-12"><div className="flex items-center justify-between"><h2 className="display-sm">Indicators</h2><span className="text-xs uppercase tracking-[0.18em] text-white/45">Observed values are evidence-based</span></div>{data.indicators.length === 0 ? <p className="mt-5 border border-white/10 p-6 text-white/55">No impact indicators have been defined yet.</p> : <div className="mt-5 grid gap-4 md:grid-cols-2">{data.indicators.map(({ indicator, comparison }) => <article key={indicator._id} className="border border-white/10 p-5"><h3 className="text-lg text-white">{indicator.name}</h3><p className="mt-1 text-sm text-white/55">{indicator.description || "No description provided."}</p><div className="mt-5 grid grid-cols-3 gap-3 text-sm"><div><p className="eyebrow">Baseline</p><p className="mt-2 text-white">{comparison.baseline} {comparison.unit}</p></div><div><p className="eyebrow">Target</p><p className="mt-2 text-white">{comparison.target === null ? "Not set" : `${comparison.target} ${comparison.unit}`}</p></div><div><p className="eyebrow">Observed</p><p className="mt-2 text-white">{comparison.observed === null ? "Not recorded" : `${comparison.observed} ${comparison.unit}`}</p></div></div>{comparison.progressToTarget !== null && <p className="mt-5 text-sm text-blue-100">Progress toward target: {comparison.progressToTarget}%</p>}{user && ["ADMIN", "UNIVERSITY", "INDUSTRY"].includes(user.role) && <form onSubmit={(event) => void addObservation(event, indicator._id)} className="mt-5 flex flex-wrap gap-2"><input name="observedValue" required type="number" step="any" placeholder={`Observed (${indicator.unit})`} className="input" /><input name="measurementDate" required type="date" className="input" /><button disabled={saving} className="button-secondary">Record observation</button></form>}</article>)}</div>}</section>
      <section className="mt-12"><h2 className="display-sm">Scenarios</h2>{data.scenarios.length === 0 ? <p className="mt-5 border border-white/10 p-6 text-white/55">No scenario estimates have been created.</p> : <div className="mt-5 grid gap-4 md:grid-cols-2">{data.scenarios.map((scenario) => <article key={scenario._id} className="border border-amber-300/20 p-5"><p className="eyebrow">Estimate — not observed outcome</p><h3 className="mt-2 text-lg text-white">{scenario.name}</h3><p className="mt-2 text-sm text-white/65">{scenario.proposedIntervention}</p><p className="mt-4 text-sm text-white/45">Method: {scenario.estimationMethod}</p></article>)}</div>}</section>
    </>}
  </main>;
}
export default function Page() { return <ProtectedRoute allowedRole={["CITIZEN", "STUDENT", "UNIVERSITY", "INDUSTRY", "ADMIN"]}><Content /></ProtectedRoute>; }
