"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ProtectedRoute } from "@/components/auth/protected-route";
import { getStudentTeams } from "@/services/student.service";
import type { StudentTeam } from "@/types/project";

function Content(){const[teams,setTeams]=useState<StudentTeam[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=useCallback(()=>{setLoading(true);setError("");getStudentTeams().then(setTeams).catch(()=>setError("Unable to load your teams.")).finally(()=>setLoading(false))},[]);useEffect(()=>{Promise.resolve().then(load)},[load]);return <main className="mx-auto max-w-6xl px-5 py-16"><Link href="/student" className="text-link">← Student workspace</Link><p className="eyebrow mt-10">Student collaboration / teams</p><h1 className="display-md mt-3">My teams</h1>{loading&&<p className="mt-8 text-white/50">Loading your teams…</p>}{error&&<p className="mt-8 text-red-200" role="alert">{error} <button className="underline" onClick={load}>Retry</button></p>}{!loading&&!error&&!teams.length&&<p className="mt-8 border border-dashed border-white/20 p-8 text-white/55">You haven&apos;t been added to any project teams yet.</p>}<div className="mt-8 grid gap-5 md:grid-cols-2">{teams.map((team)=><article key={team.id} className="border border-white/10 p-6"><p className="eyebrow">{team.project.status}</p><h2 className="mt-3 text-xl text-white">{team.name}</h2><p className="mt-2 text-white/65">{team.project.title}</p><p className="mt-4 text-sm text-white/55">{team.project.university && typeof team.project.university!=="string" ? team.project.university.name : "University project"} · {team.project.progress}% complete</p><p className="mt-2 text-sm text-white/55">{team.project.completedMilestones}/{team.project.totalMilestones} milestones complete</p><Link href={`/student/teams/${team.id}`} className="button-primary mt-5 inline-flex">View Team</Link></article>)}</div></main>}
export default function Page(){return <ProtectedRoute allowedRole="STUDENT"><Content/></ProtectedRoute>}
