"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ProtectedRoute } from "@/components/auth/protected-route";
import { getChallengePassport } from "@/services/problem.service";
import type { ChallengePassport } from "@/types/passport";
function Content() { const params = useParams<{ id: string }>(); const id = Array.isArray(params.id) ? params.id[0] : params.id; const [passport, setPassport] = useState<ChallengePassport | null>(null); const [error, setError] = useState(""); useEffect(() => { getChallengePassport(id).then(setPassport).catch(() => setError("Unable to load the Challenge Passport.")); }, [id]); if (error) return <main className="mx-auto max-w-5xl px-5 py-16"><p className="text-red-200" role="alert">{error}</p></main>; if (!passport) return <main className="mx-auto max-w-5xl px-5 py-16"><p className="text-white/50">Loading Challenge Passport…</p></main>; return <main className="mx-auto max-w-5xl px-5 py-16"><Link href={`/citizen/problems/${id}`} className="text-link">← Back to problem</Link><p className="eyebrow mt-10">Challenge Passport / {passport.problem.status}</p><h1 className="display-md mt-3">{passport.problem.title}</h1><p className="mt-3 text-white/55">{passport.problem.category} · {passport.problem.location?.city}, {passport.problem.location?.state}</p><section className="mt-10 border border-white/10 p-6"><p className="eyebrow">Journey timeline</p><ol className="mt-6 space-y-4">{passport.events.map((event, index) => <li key={`${event.type}-${event.timestamp}-${index}`} className="border-l border-blue-300/40 pl-5"><div className="flex flex-wrap justify-between gap-2"><p className="text-white">{event.title}</p><time className="text-xs uppercase tracking-widest text-white/40">{new Date(event.timestamp).toLocaleString()}</time></div><p className="mt-1 text-xs uppercase tracking-widest text-blue-100/60">{event.status}</p>{event.detail && <p className="mt-2 text-sm text-white/60">{event.detail}</p>}</li>)}</ol></section><section className="mt-6 border border-white/10 p-6"><p className="eyebrow">Related delivery</p>{!passport.projects.length && <p className="mt-3 text-white/55">No university project has been created yet.</p>}{passport.projects.map((project) => <div key={project.id} className="mt-4 border-t border-white/10 pt-4"><div className="flex flex-wrap justify-between gap-3"><p className="text-white">{project.title}</p><p className="eyebrow">{project.progress}% · {project.status}</p></div><p className="mt-2 text-sm text-white/55">{project.completedMilestones}/{project.totalMilestones} milestones complete{project.team ? ` · ${project.team.name}` : " · Team formation pending"}</p></div>)}</section></main>; }
export default function Page() { return <ProtectedRoute allowedRole={["CITIZEN", "STUDENT"]}><Content /></ProtectedRoute>; }

