"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ProtectedRoute } from "@/components/auth/protected-route";
import { getNotifications, markAllNotificationsRead, markNotificationRead } from "@/services/notification.service";
import type { AppNotification } from "@/types/notification";
import { USER_ROLES } from "@/types/auth";

function Content() { const [items, setItems] = useState<AppNotification[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const load = useCallback(() => { getNotifications().then((data) => setItems(data.notifications)).catch(() => setError("Unable to load notifications.")).finally(() => setLoading(false)); }, []); useEffect(() => { void load(); }, [load]); const read = async (item: AppNotification) => { if (!item.isRead) { await markNotificationRead(item.id); setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, isRead: true } : entry)); } }; const destination = (item: AppNotification) => item.relatedType === "PROBLEM" && item.relatedId ? `/citizen/problems/${item.relatedId}` : item.relatedType === "SOLUTION" && item.relatedId ? `/university/projects` : item.relatedType === "PROJECT" && item.relatedId ? `/university/projects/${item.relatedId}` : "/notifications"; return <main className="mx-auto max-w-4xl px-5 py-16"><p className="eyebrow">Workspace updates</p><div className="flex flex-wrap items-end justify-between gap-4"><h1 className="display-md mt-3">Notifications</h1><button className="button-secondary" onClick={async () => { await markAllNotificationsRead(); setItems((current) => current.map((item) => ({ ...item, isRead: true }))); }}>Mark all read</button></div>{loading && <p className="mt-8 text-white/50">Loading notifications…</p>}{error && <p className="mt-8 text-red-200" role="alert">{error}</p>}{!loading && !error && !items.length && <p className="mt-8 border border-dashed border-white/20 p-8 text-white/55">No notifications yet.</p>}<div className="mt-8 space-y-3">{items.map((item) => <Link key={item.id} href={destination(item)} onClick={() => void read(item)} className={`block border p-5 ${item.isRead ? "border-white/10" : "border-blue-300/40"}`}><div className="flex flex-wrap justify-between gap-3"><p className="text-white">{item.title}</p><p className="eyebrow">{new Date(item.createdAt).toLocaleString()}</p></div><p className="mt-2 text-sm text-white/65">{item.message}</p></Link>)}</div></main>; }
export default function Page() { return <ProtectedRoute allowedRole={[...USER_ROLES]}><Content /></ProtectedRoute>; }
